// Mocks generated by Mockito 5.4.4 from annotations
// in GospelWisdom/test/services/post_login_data_loader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:GospelWisdom/models/chapter.dart' as _i12;
import 'package:GospelWisdom/models/chapter_summary.dart' as _i11;
import 'package:GospelWisdom/models/gospel.dart' as _i10;
import 'package:GospelWisdom/models/journal_entry.dart' as _i13;
import 'package:GospelWisdom/models/scenario.dart' as _i8;
import 'package:GospelWisdom/models/verse.dart' as _i3;
import 'package:GospelWisdom/services/enhanced_supabase_service.dart' as _i4;
import 'package:GospelWisdom/services/progressive_scenario_service.dart' as _i6;
import 'package:GospelWisdom/services/service_locator.dart' as _i15;
import 'package:GospelWisdom/services/supabase_auth_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerse_1 extends _i1.SmartFake implements _i3.Verse {
  _FakeVerse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnhancedSupabaseService_2 extends _i1.SmartFake
    implements _i4.EnhancedSupabaseService {
  _FakeEnhancedSupabaseService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseAuthService_3 extends _i1.SmartFake
    implements _i5.SupabaseAuthService {
  _FakeSupabaseAuthService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProgressiveScenarioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressiveScenarioService extends _i1.Mock
    implements _i6.ProgressiveScenarioService {
  MockProgressiveScenarioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasScenarios => (super.noSuchMethod(
        Invocation.getter(#hasScenarios),
        returnValue: false,
      ) as bool);

  @override
  int get scenarioCount => (super.noSuchMethod(
        Invocation.getter(#scenarioCount),
        returnValue: 0,
      ) as int);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i8.Scenario> searchScenarios(
    String? query, {
    int? maxResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [query],
          {#maxResults: maxResults},
        ),
        returnValue: <_i8.Scenario>[],
      ) as List<_i8.Scenario>);

  @override
  _i7.Future<List<_i8.Scenario>> searchScenariosAsync(
    String? query, {
    int? maxResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenariosAsync,
          [query],
          {#maxResults: maxResults},
        ),
        returnValue: _i7.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i7.Future<List<_i8.Scenario>>);

  @override
  _i7.Future<_i8.Scenario?> getScenario(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getScenario,
          [id],
        ),
        returnValue: _i7.Future<_i8.Scenario?>.value(),
      ) as _i7.Future<_i8.Scenario?>);

  @override
  _i7.Future<void> waitForCriticalScenarios() => (super.noSuchMethod(
        Invocation.method(
          #waitForCriticalScenarios,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refreshFromServer() => (super.noSuchMethod(
        Invocation.method(
          #refreshFromServer,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, dynamic> getLoadingProgress() => (super.noSuchMethod(
        Invocation.method(
          #getLoadingProgress,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<bool> hasNewScenariosAvailable() => (super.noSuchMethod(
        Invocation.method(
          #hasNewScenariosAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> backgroundSync({_i9.VoidCallback? onComplete}) =>
      (super.noSuchMethod(
        Invocation.method(
          #backgroundSync,
          [],
          {#onComplete: onComplete},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<void> clearAllCaches() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCaches,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [EnhancedSupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedSupabaseService extends _i1.Mock
    implements _i4.EnhancedSupabaseService {
  MockEnhancedSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i7.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i10.Gospel>> fetchGospels() => (super.noSuchMethod(
        Invocation.method(
          #fetchGospels,
          [],
        ),
        returnValue: _i7.Future<List<_i10.Gospel>>.value(<_i10.Gospel>[]),
      ) as _i7.Future<List<_i10.Gospel>>);

  @override
  _i7.Future<_i10.Gospel?> fetchGospelById(int? gospelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGospelById,
          [gospelId],
        ),
        returnValue: _i7.Future<_i10.Gospel?>.value(),
      ) as _i7.Future<_i10.Gospel?>);

  @override
  _i7.Future<void> initializeLanguages() => (super.noSuchMethod(
        Invocation.method(
          #initializeLanguages,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setCurrentLanguage(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentLanguage,
          [langCode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.ChapterSummary>> fetchChapterSummaries(
          [String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterSummaries,
          [langCode],
        ),
        returnValue: _i7.Future<List<_i11.ChapterSummary>>.value(
            <_i11.ChapterSummary>[]),
      ) as _i7.Future<List<_i11.ChapterSummary>>);

  @override
  _i7.Future<_i12.Chapter?> fetchChapterById(
    String? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterById,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<_i12.Chapter?>.value(),
      ) as _i7.Future<_i12.Chapter?>);

  @override
  _i7.Future<List<_i12.Chapter>> fetchAllChapters([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllChapters,
          [langCode],
        ),
        returnValue: _i7.Future<List<_i12.Chapter>>.value(<_i12.Chapter>[]),
      ) as _i7.Future<List<_i12.Chapter>>);

  @override
  _i7.Future<List<_i8.Scenario>> fetchScenariosByChapter(
    String? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenariosByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i7.Future<List<_i8.Scenario>>);

  @override
  _i7.Future<_i8.Scenario?> fetchScenarioById(
    int? scenarioId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioById,
          [
            scenarioId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<_i8.Scenario?>.value(),
      ) as _i7.Future<_i8.Scenario?>);

  @override
  _i7.Future<List<_i8.Scenario>> searchScenarios(
    String? query, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchScenarios,
          [
            query,
            langCode,
          ],
        ),
        returnValue: _i7.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i7.Future<List<_i8.Scenario>>);

  @override
  _i7.Future<List<_i8.Scenario>> fetchScenarios({
    int? limit = 2000,
    int? offset = 0,
    String? langCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarios,
          [],
          {
            #limit: limit,
            #offset: offset,
            #langCode: langCode,
          },
        ),
        returnValue: _i7.Future<List<_i8.Scenario>>.value(<_i8.Scenario>[]),
      ) as _i7.Future<List<_i8.Scenario>>);

  @override
  _i7.Future<int> getScenarioCount() => (super.noSuchMethod(
        Invocation.method(
          #getScenarioCount,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i3.Verse>> fetchVersesByChapter(
    String? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVersesByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<List<_i3.Verse>>.value(<_i3.Verse>[]),
      ) as _i7.Future<List<_i3.Verse>>);

  @override
  _i7.Future<_i3.Verse> fetchRandomVerseByChapter(
    String? chapterId, [
    String? langCode,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomVerseByChapter,
          [
            chapterId,
            langCode,
          ],
        ),
        returnValue: _i7.Future<_i3.Verse>.value(_FakeVerse_1(
          this,
          Invocation.method(
            #fetchRandomVerseByChapter,
            [
              chapterId,
              langCode,
            ],
          ),
        )),
      ) as _i7.Future<_i3.Verse>);

  @override
  _i7.Future<_i8.Scenario?> fetchRandomScenario() => (super.noSuchMethod(
        Invocation.method(
          #fetchRandomScenario,
          [],
        ),
        returnValue: _i7.Future<_i8.Scenario?>.value(),
      ) as _i7.Future<_i8.Scenario?>);

  @override
  _i7.Future<int> fetchScenarioCount(String? chapterId) => (super.noSuchMethod(
        Invocation.method(
          #fetchScenarioCount,
          [chapterId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> insertJournalEntry(_i13.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertJournalEntry,
          [entry],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i13.JournalEntry>> fetchJournalEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchJournalEntries,
          [],
        ),
        returnValue:
            _i7.Future<List<_i13.JournalEntry>>.value(<_i13.JournalEntry>[]),
      ) as _i7.Future<List<_i13.JournalEntry>>);

  @override
  _i7.Future<void> insertFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [scenarioTitle],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorite(String? scenarioTitle) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [scenarioTitle],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<String>> fetchFavorites() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<Map<String, dynamic>> getTranslationCoverage([String? langCode]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslationCoverage,
          [langCode],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<bool> refreshTranslationViews() => (super.noSuchMethod(
        Invocation.method(
          #refreshTranslationViews,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  bool isLanguageSupported(String? langCode) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [langCode],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getLanguageDisplayName(
    String? langCode, {
    bool? useNative = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageDisplayName,
          [langCode],
          {#useNative: useNative},
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageDisplayName,
            [langCode],
            {#useNative: useNative},
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ServiceLocator].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceLocator extends _i1.Mock implements _i15.ServiceLocator {
  MockServiceLocator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EnhancedSupabaseService get enhancedSupabaseService =>
      (super.noSuchMethod(
        Invocation.getter(#enhancedSupabaseService),
        returnValue: _FakeEnhancedSupabaseService_2(
          this,
          Invocation.getter(#enhancedSupabaseService),
        ),
      ) as _i4.EnhancedSupabaseService);

  @override
  _i5.SupabaseAuthService get supabaseAuthService => (super.noSuchMethod(
        Invocation.getter(#supabaseAuthService),
        returnValue: _FakeSupabaseAuthService_3(
          this,
          Invocation.getter(#supabaseAuthService),
        ),
      ) as _i5.SupabaseAuthService);

  @override
  void setEnhancedSupabaseService(_i4.EnhancedSupabaseService? service) =>
      super.noSuchMethod(
        Invocation.method(
          #setEnhancedSupabaseService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSupabaseAuthService(_i5.SupabaseAuthService? service) =>
      super.noSuchMethod(
        Invocation.method(
          #setSupabaseAuthService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
